[package]
name = "puccinia"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "puccinia_server"
path = "src/server/main.rs"

[dependencies]
chrono = "0.4"
coinnect = "0.5"
decimal = "2.0"
hyper-native-tls = "0.2"
mime = "0.2"
rand = "0.4"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.rocket_contrib]
version = "0.3.6"
default-features = false
features = ["handlebars_templates"]

[dependencies.xml-rs]
version = "0.7"
path = "xml-rs"
