[package]
name = "puccinia"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
chrono = "0.4"
coinnect = "0.5"
decimal = "2.0"
hyper-native-tls = "0.2"
mime = "0.2"
rand = "0.4"

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.xml-rs]
version = "0.7"
path = "xml-rs"
